from . import back
from . import help
from . import start
from . import admin
from . import functions
from . import resume
from . import project
from . import shoxa_qoshiq
from . import admin_panel
from . import tabrik
